
CREATE TABLE IF NOT EXISTS system_logs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  log_uuid CHAR(36) NOT NULL,
  log_type VARCHAR(50) NOT NULL,
  source VARCHAR(20) NOT NULL DEFAULT 'php',
  status VARCHAR(20) NOT NULL DEFAULT 'info',
  nice_message VARCHAR(255) NOT NULL,
  message TEXT NULL,
  details_json JSON NULL,
  user_id BIGINT UNSIGNED NULL,
  session_id VARCHAR(128) NULL,
  request_method VARCHAR(12) NULL,
  request_path VARCHAR(255) NULL,
  request_origin VARCHAR(255) NULL,
  request_ip VARCHAR(64) NULL,
  user_agent VARCHAR(512) NULL,
  device_fingerprint VARCHAR(128) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_ota_system_logs_uuid (log_uuid),
  KEY idx_ota_system_logs_type (log_type),
  KEY idx_ota_system_logs_source (source),
  KEY idx_ota_system_logs_status (status),
  KEY idx_ota_system_logs_user (user_id),
  KEY idx_ota_system_logs_session (session_id),
  KEY idx_ota_system_logs_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS blocker_logs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  log_uuid CHAR(36) NOT NULL,
  session_id VARCHAR(128) NULL,
  user_id BIGINT UNSIGNED NULL,
  blocker_type VARCHAR(40) NOT NULL,
  blocker_reason VARCHAR(120) NULL,
  nice_message VARCHAR(255) NOT NULL,
  message TEXT NULL,
  details_json JSON NULL,
  is_fullscreen TINYINT(1) NOT NULL DEFAULT 0,
  fullscreen_gap_seconds INT UNSIGNED NOT NULL DEFAULT 0,
  tab_switch_count INT UNSIGNED NOT NULL DEFAULT 0,
  devtools_count INT UNSIGNED NOT NULL DEFAULT 0,
  visibility_count INT UNSIGNED NOT NULL DEFAULT 0,
  keyboard_count INT UNSIGNED NOT NULL DEFAULT 0,
  contextmenu_count INT UNSIGNED NOT NULL DEFAULT 0,
  request_ip VARCHAR(64) NULL,
  user_agent VARCHAR(512) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_ota_blocker_logs_uuid (log_uuid),
  KEY idx_ota_blocker_type (blocker_type),
  KEY idx_ota_blocker_session (session_id),
  KEY idx_ota_blocker_user (user_id),
  KEY idx_ota_blocker_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
